/**
 * ktor-sample
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package webapi.models

import com.fasterxml.jackson.annotation.JsonProperty
/**
 * 
 *
 * @param id 
 * @param name 
 * @param email 
 */


data class User (


    @JsonProperty("id")
    val id: kotlin.Int,


    @JsonProperty("name")
    val name: kotlin.String,


    @JsonProperty("email")
    val email: kotlin.String? = null

)

